swagger: "2.0"
info:
  version: "0.0.1"
  title: HRChat
# during dev, should point to your local machine
host: localhost:3000
Authorization: Bearer <>

# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /auth/trainer:
    x-swagger-router-controller: auth
    post:
      tags:
      - "auth"
      operationId: signInTrainer
      description: sigin Trainer
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "login as trainer in website"
        required: true
        schema:
          $ref: "#/definitions/Trainer"
      responses:
        default:
          description: "successful operation"
  /auth/student:
    x-swagger-router-controller: auth
    post:
      tags:
      - "auth"
      operationId: signInStudent
      description: signIn Student
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created student and connecting to the room"
        required: true
        schema:
          $ref: "#/definitions/Student"
      responses:
        default:
          description: "successful operation"
  /room:
    x-swagger-router-controller: room
    post:
      security:
      - bearerAuth: []
      tags:
      - "room"
      operationId: createRoom
      description: create Room
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: authorization
        type: string
        required: true
      - in: "body"
        name: "body"
        description: "Created room"
        required: true
        schema:
          $ref: "#/definitions/Room"
      responses:
        default:
          description: "successful operation"
  /room/:
    x-swagger-router-controller: room
    get:
      security:
      - bearerAuth: []
      tags:
      - "room"
      operationId: getRoom
      description: Опрелеление студент или тренер
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: authorization
        type: string
        required: true
      responses:
        default:
          description: "successful operation"
  /room/student:
    x-swagger-router-controller: room
    delete:
      security:
      - bearerAuth: []
      tags:
      - "room"
      operationId: dateteStudent
      description: Delete Student in Room
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: authorization
        type: string
        required: true
      - in: "body"
        name: "body"
        description: "Delete Student in Room"
        required: true
        schema:
          $ref: "#/definitions/SudentId"
      responses:
        default:
          description: "successful operation"
  /room/:id:
    x-swagger-router-controller: room
    get:
      security:
      - bearerAuth: []
      tags:
      - "room"
      operationId: getRoomId
      description: get Student in Room
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: authorization
        type: string
        required: true
      responses:
        default:
          description: "successful operation"
  /swagger:
    x-swagger-pipe: swagger_raw
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only
# complex objects have schema definitions
definitions:
  Trainer:
    type: "object"
    properties:
      login:
        type: "string"
      password:
        type: "string"
    xml:
      name: "Trainer"
  Student:
    type: "object"
    properties:
      name:
        type: "string"
      roomId:
        type: "integer"
    xml:
      name: "Student"
  Room:
    type: "object"
    properties:
      timer:
        type: "integer"
      count_students:
        type: "integer"
      is_championship:
        type: "boolean"
      number_round:
        type: "integer"
    xml:
      name: "Room"
  SudentId:
    type: "object"
    properties:
      id:
        type: "integer"
    xml:
      name: "SudentId"
